version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: ${CONTAINER_PREFIX}nginx
    ports:
      - "${NGINX_PORT}:8888"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - keycloak

  app1:
    build: ./app1
    container_name: ${CONTAINER_PREFIX}app1
    ports:
      - "${APP1_PORT}:8001"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - postgres
      - redis
      - memcached
      - rabbitmq

  app2:
    build: ./app2
    container_name: ${CONTAINER_PREFIX}app2
    ports:
      - "${APP2_PORT}:8002"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - postgres
      - redis
      - memcached
      - rabbitmq

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: ${CONTAINER_PREFIX}keycloak
    ports:
      - "${KEYCLOAK_PORT}:8003"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: ${CONTAINER_PREFIX}postgres
    ports:
      - "${POSTGRES_PORT}:30001"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:latest
    container_name: ${CONTAINER_PREFIX}redis
    ports:
      - "${REDIS_PORT}:6379"

  memcached:
    image: memcached:latest
    container_name: ${CONTAINER_PREFIX}memcached
    ports:
      - "${MEMCACHED_PORT}:11211"

  rabbitmq:
    image: rabbitmq:latest
    container_name: ${CONTAINER_PREFIX}rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
