

services:
  nginx:
    image: nginx:latest
    container_name: ${CONTAINER_PREFIX}nginx
    ports:
      - "${NGINX_PORT}:8888"
    volumes:
      - ./nginx/sites-enabled/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - keycloak

  app1:
    build: ./app1
    container_name: ${CONTAINER_PREFIX}app1
    ports:
      - "${APP1_PORT}:8001"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - postgres
      - redis
      - memcached
      - rabbitmq

  app2:
    build: ./app2
    container_name: ${CONTAINER_PREFIX}app2
    ports:
      - "${APP2_PORT}:8002"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - postgres
      - redis
      - memcached
      - rabbitmq

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: ${CONTAINER_PREFIX}keycloak
    ports:
      - "${KEYCLOAK_PORT}:8003"
    environment:
      KC_HTTP_PORT: ${KEYCLOAK_PORT}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: ${CONTAINER_PREFIX}postgres
    ports:
      - "${POSTGRES_PORT}:30001"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/conf/pg_hba.conf:/etc/postgresql/pg_hba.conf

    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: ${CONTAINER_PREFIX}redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - my_network

  memcached:
    image: memcached:latest
    container_name: ${CONTAINER_PREFIX}memcached
    ports:
      - "${MEMCACHED_PORT}:11211"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${CONTAINER_PREFIX}rabbitmq
  ports:
    - "${RABBITMQ_PORT}:5672"
    - "${RABBITMQ_MANAGEMENT_PORT}:15672"
  environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

volumes:
  postgres_data:
  redis_data:

networks:
  my_network:
    driver: bridge
